/**
 * Skill Source Abstraction
 *
 * Provides uniform access to skills whether from filesystem (dev mode)
 * or VFS (compiled binary mode).
 *
 * In compiled mode (IS_COMPILED=true), skills are read from the
 * generated VFS module. In dev mode, skills are read from disk.
 */

import { chmodSync, existsSync, readdirSync, mkdirSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import type { Skill } from './types.js';

// Build-time define — set to true by bun build --define IS_COMPILED=true
declare const IS_COMPILED: boolean;

// Lazy-loaded VFS (only imported in compiled mode)
let _vfs: Map<string, Map<string, string>> | null = null;
let _skillNames: string[] | null = null;

async function getVFS() {
  if (!_vfs) {
    // Static path so the bundler resolves it during both regular and native builds.
    // A stub is generated by `prebuild` if the real VFS doesn't exist yet.
    // The real VFS is generated by scripts/generate-vfs.ts during build:native.
    const mod = await import('./generated/skills-vfs.js');
    _vfs = mod.SKILLS_VFS;
    _skillNames = mod.SKILL_NAMES;
  }
  return { vfs: _vfs!, skillNames: _skillNames! };
}

/**
 * Extract the frontmatter `description:` value from SKILL.md content.
 * Handles both inline scalars (`description: foo`) and folded/literal block
 * scalars (`description: >-` + indented lines) — block scalars are required
 * for descriptions containing `": "` so strict-YAML consumers (npx skills)
 * don't reject the file. Folded lines join with spaces.
 */
export function extractDescription(content: string): string {
  const m = content.match(/^description:[ \t]*(.*)$/m);
  if (!m) return '';
  const inline = m[1].trim();
  if (!/^[>|][+-]?$/.test(inline)) return inline;
  const lines = content.split('\n');
  const idx = lines.findIndex((l) => /^description:[ \t]*[>|][+-]?[ \t]*\r?$/.test(l));
  if (idx === -1) return '';
  const out: string[] = [];
  for (let i = idx + 1; i < lines.length; i++) {
    const line = lines[i];
    if (line.trim() === '') continue;
    if (!/^[ \t]/.test(line)) break;
    out.push(line.trim());
  }
  return out.join(' ').trim();
}

/** Check if running as a compiled binary */
export function isCompiled(): boolean {
  try {
    return typeof IS_COMPILED !== 'undefined' && IS_COMPILED;
  } catch {
    return false;
  }
}

// ── Filesystem mode (dev) ──────────────────────────────────

/**
 * Walk up from this module to the nearest package.json. Robust across
 * dev (`bun run src/cli/index.ts`), published-npm (node_modules/arra-oracle-skills),
 * and dist-bundle layouts — unlike a fixed `../skills` hop that breaks the
 * moment this file's depth changes.
 */
function findPackageRoot(): string {
  let dir = dirname(import.meta.path);
  while (dir !== dirname(dir)) {
    if (existsSync(join(dir, 'package.json'))) return dir;
    dir = dirname(dir);
  }
  return dirname(import.meta.path);
}

/** Public shelf: top-level skills/ — the curated set every channel serves. */
export function getPublicSkillsDir(): string {
  return join(findPackageRoot(), 'skills');
}

/** Vault: src/skills/ — secrets, .template. (.archive holds only the
 *  MOVED.md breadcrumb since 2026-08-22; zombies live in their own repo.) */
function getVaultSkillsDir(): string {
  return join(findPackageRoot(), 'src', 'skills');
}

/**
 * Resolve a skill name to its on-disk directory.
 * Order: public shelf (`skills/<name>`) → vault (`src/skills/<name>`) →
 * vault archive (`src/skills/.archive/<name>`).
 *
 * The archive fallback is retained but finds nothing: the 39 zombies moved to
 * Soul-Brews-Studio/arra-oracle-skills-archive on 2026-08-22, leaving only a
 * MOVED.md breadcrumb. Kept so a future retirement works without re-plumbing.
 */
function resolveSkillDir(skillName: string): string {
  const shelf = join(getPublicSkillsDir(), skillName);
  if (existsSync(shelf)) return shelf;
  const vaultRoot = getVaultSkillsDir();
  const vault = join(vaultRoot, skillName);
  if (existsSync(vault)) return vault;
  const archived = join(vaultRoot, '.archive', skillName);
  if (existsSync(archived)) return archived;
  // Fall through to vault path so existsSync checks downstream report not-found
  return vault;
}

// ── Unified API ────────────────────────────────────────────

/** Discover all available skills */
export async function discoverSkills(): Promise<Skill[]> {
  if (isCompiled()) {
    const { vfs, skillNames } = await getVFS();
    const skills: Skill[] = [];
    for (const name of skillNames) {
      const files = vfs.get(name);
      const skillMd = files?.get('SKILL.md');
      if (skillMd) {
        const hiddenMatch = skillMd.match(/hidden:\s*(true|yes)/i);
        const secretMatch = skillMd.match(/secret:\s*(true|yes)/i);
        const zombieMatch = skillMd.match(/zombie:\s*(true|yes)/i);
        skills.push({
          name,
          description: extractDescription(skillMd),
          path: `vfs://${name}`, // Virtual path marker
          ...(hiddenMatch ? { hidden: true } : {}),
          ...(secretMatch ? { secret: true } : {}),
          ...(zombieMatch ? { zombie: true } : {}),
        });
      }
    }
    return skills;
  }

  // Filesystem mode — dual root.
  // Public shelf (skills/): curated skills, every channel serves these.
  // Vault (src/skills/): secret skills. .archive/ is scanned but empty since
  // 2026-08-22 — zombies moved to arra-oracle-skills-archive. The scan stays so
  // a future retirement needs no re-plumbing.
  const listDirs = (root: string) =>
    existsSync(root)
      ? readdirSync(root, { withFileTypes: true })
          .filter((d) => d.isDirectory() && !d.name.startsWith('.'))
          .map((d) => ({ name: d.name, dir: join(root, d.name) }))
      : [];

  const shelfDirs = listDirs(getPublicSkillsDir());
  const vaultRoot = getVaultSkillsDir();
  const vaultDirs = listDirs(vaultRoot);
  const archivedDirs = listDirs(join(vaultRoot, '.archive'));

  if (shelfDirs.length === 0 && vaultDirs.length === 0 && archivedDirs.length === 0) return [];

  // A name living in two roots is a split-brain bug (e.g. a rebase resurrecting
  // src/skills/<name> after its move to the shelf) — fail loudly, never last-wins.
  const seen = new Map<string, string>();
  for (const { name, dir } of [...shelfDirs, ...vaultDirs, ...archivedDirs]) {
    const prev = seen.get(name);
    if (prev && existsSync(join(dir, 'SKILL.md')) && existsSync(join(prev, 'SKILL.md'))) {
      throw new Error(
        `Duplicate skill name "${name}" across roots: ${prev} and ${dir} — git mv one of them (shelf skills/ vs vault src/skills/).`
      );
    }
    if (!prev) seen.set(name, dir);
  }

  const skills: Skill[] = [];
  for (const { name, dir } of [...shelfDirs, ...vaultDirs, ...archivedDirs]) {
    const skillMdPath = join(dir, 'SKILL.md');
    if (existsSync(skillMdPath)) {
      const content = await Bun.file(skillMdPath).text();
      const hiddenMatch = content.match(/hidden:\s*(true|yes)/i);
      const secretMatch = content.match(/secret:\s*(true|yes)/i);
      const zombieMatch = content.match(/zombie:\s*(true|yes)/i);
      skills.push({
        name,
        description: extractDescription(content),
        path: dir,
        ...(hiddenMatch ? { hidden: true } : {}),
        ...(secretMatch ? { secret: true } : {}),
        ...(zombieMatch ? { zombie: true } : {}),
      });
    }
  }
  return skills;
}

/** Read a file from a skill (VFS or filesystem) */
export async function readSkillFile(
  skillName: string,
  relativePath: string
): Promise<string | null> {
  if (isCompiled()) {
    const { vfs } = await getVFS();
    return vfs.get(skillName)?.get(relativePath) ?? null;
  }
  const fullPath = join(resolveSkillDir(skillName), relativePath);
  if (!existsSync(fullPath)) return null;
  return Bun.file(fullPath).text();
}

/** List all files in a skill directory */
export async function listSkillFiles(skillName: string): Promise<string[]> {
  if (isCompiled()) {
    const { vfs } = await getVFS();
    const files = vfs.get(skillName);
    return files ? [...files.keys()] : [];
  }
  // Filesystem: walk the directory
  const skillDir = resolveSkillDir(skillName);
  if (!existsSync(skillDir)) return [];
  return walkDirRelative(skillDir, skillDir);
}

function walkDirRelative(dir: string, base: string): string[] {
  const files: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.name === '.DS_Store') continue;
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...walkDirRelative(fullPath, base));
    } else {
      const { relative } = require('path');
      files.push(relative(base, fullPath));
    }
  }
  return files;
}

/** Write all files from a skill to a destination directory */
export async function writeSkillToDir(
  skillName: string,
  destDir: string
): Promise<void> {
  if (isCompiled()) {
    const { vfs } = await getVFS();
    const files = vfs.get(skillName);
    if (!files) return;
    writeVfsTree(files, destDir);
    return;
  }

  // Filesystem mode: use cpr (handled by caller)
  // This function is only needed for VFS mode — in fs mode,
  // the caller uses cpr() directly from the skill.path
}

/**
 * Materialize one compiled skill tree while restoring executable script modes.
 *
 * The VFS stores text, not POSIX metadata. Without this step a compiled install
 * delivered Python/shell helpers as 0644 even when the source was tracked 0755.
 * Restrict mode restoration to shebang files below scripts/; ordinary skill and
 * reference documents remain non-executable.
 */
export function writeVfsTree(files: Map<string, string>, destDir: string): void {
  for (const [relPath, content] of files) {
    const fullPath = join(destDir, relPath);
    const dir = dirname(fullPath);
    if (!existsSync(dir)) {
      mkdirSync(dir, { recursive: true });
    }
    writeFileSync(fullPath, content, { mode: 0o644 });
    // `mode` only applies when writeFileSync creates a file. Normalize an
    // existing destination too, so reinstalling cannot preserve stale execute
    // bits on documents or on scripts that no longer have a shebang.
    chmodSync(fullPath, 0o644);
    const normalized = relPath.replaceAll('\\', '/');
    if (normalized.startsWith('scripts/') && content.startsWith('#!')) {
      chmodSync(fullPath, 0o755);
    }
  }
}

/** Check if a skill has hooks */
export async function skillHasHooks(skillName: string): Promise<boolean> {
  if (isCompiled()) {
    const { vfs } = await getVFS();
    const files = vfs.get(skillName);
    return files?.has('hooks/hooks.json') ?? false;
  }
  return existsSync(join(resolveSkillDir(skillName), 'hooks', 'hooks.json'));
}
